* FunStuff
A place for all the fun stuff I do.

** GNU-Parallel
GNU Parallel is a program for running command-line tools in parallel.

map.pl and reduce.pl implement a Map/Reduce analysis of the flight
data set. You run the analysis
using the command:

#+BEGIN_EXAMPLE
    cat On_Time_Performance_1H2012.csv | parallel --pipe --blocksize 64M ./map.pl | ./reduce.pl
#+END_EXAMPLE

** LEGO
Various experiments with LEGO Mindstorm. Most of these experiments
have been published in Alt om DATA.

** Comal
Retrocomputing in COMAL-80 (using OpenComal).

  - fib.lst :: Fibonacci numbers
  - sieve.lst :: finding prime numbers
  - brussel.lst :: simulation of Brusselator using simple Euler integrator

** JavaScript
Just a couple of JavaScripts experiments.

  - graph.js :: a "library" for handling directed acyclic graphs.

** Extensions
A model extension for Node.js and Python. C++ classes are wrapped as Node.js and Python classes.

  - person.cpp and book.cpp :: C++ classes
  - person_wrap.cpp and book_wrap.cpp :: Wrapper classes (Node.js).
  - py_person.cpp and py_book.cpp :: Wrapper classes (Python).

Notice that both Python 2 and 3 are supported.

Building C++ classes:
#+BEGIN_EXAMPLE
make
#+END_EXAMPLE

Building Node.js extension:

#+BEGIN_EXAMPLE
node-waf configure
node-waf build
sudo node-waf install
#+END_EXAMPLE

** Misc
Just a collection of small programs.

  - hailstone.c :: generating hailstone series (see http://en.wikipedia.org/wiki/Collatz_conjecture)
  - fraction.py :: implementation of rational number arithmetic in Python.
  - opg1A.py and opg3A.py :: simulations of Svante's home work in probability.
  - greeting.cob :: tribute to Grace Hopper.
